apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
 name: alerts-consumer             # Unique name for this consumer
 namespace: alerts-demo
 annotations:
  kubernetes.io/ingress.class: kong
username: alerts               # Username for this consumer
custom_id: alerts-consumer-1              # Unique ID for this consumer
credentials:
 - alerts-apikey