apiVersion: v1
kind: Secret
metadata:
 name: alerts-apikey               # Must match name referenced in KongConsumer
 namespace: alerts-demo
 labels:
   konghq.com/credential: key-auth
type: Opaque
stringData:
 kongCredType: key-auth
 key: my-secret-key               # Your chosen API key value
