apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: alerts-demo
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: alerts-demo
subjects:
- kind: ServiceAccount
  name: default
  namespace: alerts-demo
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io 